// ================================================================
// PATTERN TYPES — subtypes for all 15 patterns
// Each pattern has 3-6 types with triggers, DS, and example
// ================================================================

export interface PatternType {
  name       : string;
  description: string;
  triggers   : string[];
  dataStructure: string;
  approach   : string;
  example    : string;
  complexity : { time: string; space: string };
}

export interface PatternWithTypes {
  id    : string;
  name  : string;
  icon  : string;
  color : string;
  types : PatternType[];
}

export const PATTERN_TYPES: PatternWithTypes[] = [
  {
    id: 'sliding-window', name: 'Sliding Window', icon: '🪟', color: '#10b981',
    types: [
      {
        name: 'Fixed-Size Window',
        description: 'Window size k is given. Slide it one step at a time, add right element, remove left.',
        triggers: ['subarray of size k', 'exactly k elements', 'window of size k'],
        dataStructure: 'Array + two pointers (or deque for max/min)',
        approach: 'Init window of k. For each new element: add right, remove leftmost. Track result.',
        example: 'Max sum subarray of size k → maintain running sum, subtract outgoing, add incoming',
        complexity: { time: 'O(n)', space: 'O(1) or O(k)' },
      },
      {
        name: 'Variable-Size Window (At Most K)',
        description: 'Expand right freely, shrink left when constraint breaks. Find longest valid window.',
        triggers: ['longest substring', 'maximum length', 'at most k distinct', 'no repeats'],
        dataStructure: 'HashMap (char→count) + two pointers',
        approach: 'Expand right. When invalid, shrink left until valid. Track max window size.',
        example: 'Longest substring without repeating characters → shrink when duplicate appears',
        complexity: { time: 'O(n)', space: 'O(k)' },
      },
      {
        name: 'Variable-Size Window (Exactly = Target)',
        description: 'Count subarrays with exactly sum/count. Use: f(exactly k) = f(at most k) - f(at most k-1).',
        triggers: ['count subarrays', 'exactly sum k', 'number of subarrays with', 'subarrays equal to'],
        dataStructure: 'HashMap (prefix sum) or two-pass sliding window',
        approach: 'count(exactly k) = atMost(k) - atMost(k-1). Or prefix sum + hashmap.',
        example: 'Count subarrays with sum = k → use prefix sum hashmap',
        complexity: { time: 'O(n)', space: 'O(n)' },
      },
      {
        name: 'Sliding Window with Deque (Min/Max)',
        description: 'Track maximum or minimum in current window efficiently using monotonic deque.',
        triggers: ['max in window', 'min in window', 'sliding window maximum', 'window range'],
        dataStructure: 'Deque (monotonic) + array',
        approach: 'Deque stores indices. Front = max. Remove from front if out of window. Remove from back if smaller.',
        example: 'Sliding window maximum → monotonic decreasing deque',
        complexity: { time: 'O(n)', space: 'O(k)' },
      },
    ],
  },
  {
    id: 'two-pointers', name: 'Two Pointers', icon: '👆', color: '#f59e0b',
    types: [
      {
        name: 'Opposite Ends (Converging)',
        description: 'Left pointer starts at 0, right at end. Move toward each other based on comparison.',
        triggers: ['sorted array', 'pair sum', 'two sum sorted', 'container water', 'palindrome check', 'triplets'],
        dataStructure: 'Sorted array',
        approach: 'If sum < target → move left right. If sum > target → move right left. If equal → found.',
        example: 'Two Sum II (sorted array) → l=0, r=n-1, converge',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Same Direction (Fast-Read)',
        description: 'Both pointers go left→right. Slow pointer tracks write position, fast reads ahead.',
        triggers: ['remove duplicates', 'remove element', 'move zeros', 'partition array', 'in-place modify'],
        dataStructure: 'Array (in-place)',
        approach: 'slow=0, fast=0. When condition met, write arr[slow]=arr[fast], slow++. fast always increments.',
        example: 'Remove duplicates in-place → slow tracks unique position',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Fast-Slow Pointers (Floyd\'s)',
        description: 'Slow moves 1x, fast moves 2x. Used for cycle detection and finding midpoints.',
        triggers: ['cycle detection', 'linked list middle', 'happy number', 'find loop start', 'duplicate number'],
        dataStructure: 'Linked List or implicit cycle',
        approach: 'slow=fast=head. Move until they meet (cycle) or fast reaches null (no cycle).',
        example: 'Detect cycle in linked list → meet? → cycle exists',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Three Pointers / Multi-Pass',
        description: 'Sort + fix one element, use two-pointer for the rest. Used for kSum problems.',
        triggers: ['3sum', '4sum', 'triplets that sum', 'closest sum', 'k sum'],
        dataStructure: 'Sorted array',
        approach: 'Sort. For each i, use two-pointer on i+1..n-1. Skip duplicates.',
        example: '3Sum → sort, for each a, two-pointer for -a = b+c',
        complexity: { time: 'O(n²)', space: 'O(1)' },
      },
    ],
  },
  {
    id: 'binary-search', name: 'Binary Search', icon: '🔍', color: '#6366f1',
    types: [
      {
        name: 'Classic Search in Sorted Array',
        description: 'Find element in sorted array. Eliminate half each step.',
        triggers: ['sorted array', 'search target', 'find position', 'O(log n)'],
        dataStructure: 'Sorted array',
        approach: 'lo=0, hi=n-1. mid=(lo+hi)//2. If arr[mid]==target found. Adjust lo/hi.',
        example: 'Search in rotated sorted array → check which half is sorted',
        complexity: { time: 'O(log n)', space: 'O(1)' },
      },
      {
        name: 'Binary Search on Answer Space',
        description: 'Answer is a range [lo, hi]. Binary search on the ANSWER, not the array.',
        triggers: ['minimize the maximum', 'maximize the minimum', 'minimum capacity', 'at least k', 'feasibility check'],
        dataStructure: 'Custom check function (monotonic condition)',
        approach: 'Define canDo(x) as monotonic. Binary search on x. Find smallest x where canDo(x)=true.',
        example: 'Koko eating bananas → binary search on speed k, check if can finish in H hours',
        complexity: { time: 'O(n log(max))', space: 'O(1)' },
      },
      {
        name: 'Find First/Last Occurrence',
        description: 'Find leftmost or rightmost position of target. Use lo<=hi with careful boundary.',
        triggers: ['first occurrence', 'last occurrence', 'count occurrences', 'search range', 'leftmost'],
        dataStructure: 'Sorted array',
        approach: 'For leftmost: when found, hi=mid-1. For rightmost: when found, lo=mid+1.',
        example: 'Find first and last position of element in sorted array',
        complexity: { time: 'O(log n)', space: 'O(1)' },
      },
      {
        name: 'Binary Search in 2D Matrix',
        description: 'Treat 2D matrix as 1D sorted array. mid maps to row=mid//cols, col=mid%cols.',
        triggers: ['sorted matrix', 'search 2D', 'matrix where each row sorted', 'search matrix'],
        dataStructure: '2D sorted array',
        approach: 'lo=0, hi=rows*cols-1. mid → row=mid//cols, col=mid%cols.',
        example: 'Search a 2D Matrix → treat as 1D array',
        complexity: { time: 'O(log(m*n))', space: 'O(1)' },
      },
    ],
  },
  {
    id: 'fast-slow-pointers', name: 'Fast & Slow Pointers', icon: '⚡', color: '#8b5cf6',
    types: [
      {
        name: 'Cycle Detection',
        description: 'Detect if a linked list or sequence has a cycle.',
        triggers: ['cycle', 'loop', 'circular', 'detect if linked list has cycle'],
        dataStructure: 'Linked list / implicit sequence',
        approach: 'slow=fast=head. Loop: slow=slow.next, fast=fast.next.next. If they meet → cycle.',
        example: 'Linked List Cycle → do slow and fast meet?',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Cycle Start Detection',
        description: 'Find where the cycle begins using the 2-pointer meeting trick.',
        triggers: ['find start of cycle', 'find loop entry', 'cycle start node'],
        dataStructure: 'Linked list',
        approach: 'After slow/fast meet, reset one to head. Move both 1 step at a time. They meet at cycle start.',
        example: 'Linked List Cycle II → find where cycle begins',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Middle of Linked List',
        description: 'When fast reaches end, slow is at middle.',
        triggers: ['middle of linked list', 'find middle', 'split list in half'],
        dataStructure: 'Linked list',
        approach: 'slow=fast=head. While fast and fast.next exist: slow=slow.next, fast=fast.next.next.',
        example: 'Middle of Linked List → slow stops at mid',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
    ],
  },
  {
    id: 'merge-intervals', name: 'Merge Intervals', icon: '🔗', color: '#ec4899',
    types: [
      {
        name: 'Merge Overlapping Intervals',
        description: 'Sort by start, merge intervals that overlap.',
        triggers: ['merge intervals', 'overlapping intervals', 'combine ranges', 'union of intervals'],
        dataStructure: 'Array of pairs, sorted',
        approach: 'Sort by start. For each interval: if start <= prev.end → extend. Else → push new.',
        example: 'Merge Intervals → [[1,3],[2,6]] → [[1,6]]',
        complexity: { time: 'O(n log n)', space: 'O(n)' },
      },
      {
        name: 'Insert Interval',
        description: 'Insert a new interval into a sorted list, merging overlaps.',
        triggers: ['insert interval', 'add interval', 'insert and merge'],
        dataStructure: 'Sorted array of intervals',
        approach: 'Add all before newInterval. Merge overlapping ones. Add remaining.',
        example: 'Insert Interval → insert [2,5] into [[1,3],[6,9]]',
        complexity: { time: 'O(n)', space: 'O(n)' },
      },
      {
        name: 'Interval Scheduling (Min Rooms)',
        description: 'Count max overlapping intervals at any point → minimum resources needed.',
        triggers: ['minimum meeting rooms', 'minimum platforms', 'maximum overlap', 'how many rooms'],
        dataStructure: 'Min-heap (end times) or events array',
        approach: 'Sort by start. Min-heap of end times. If heap.top <= start → pop (room freed). Push end.',
        example: 'Meeting Rooms II → minimum conference rooms',
        complexity: { time: 'O(n log n)', space: 'O(n)' },
      },
    ],
  },
  {
    id: 'cyclic-sort', name: 'Cyclic Sort', icon: '🔄', color: '#06b6d4',
    types: [
      {
        name: 'Basic Cyclic Sort',
        description: 'Array has values 1..n. Place each number at index i-1.',
        triggers: ['sort array 1 to n', 'values in range 1 to n', 'place at correct index'],
        dataStructure: 'Array (in-place)',
        approach: 'i=0. While i<n: j=arr[i]-1. If arr[i]!=arr[j] → swap. Else → i++.',
        example: 'Sort array containing 1..n → each value goes to index val-1',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Find Missing Number',
        description: 'After cyclic sort, find index where arr[i] != i+1 → missing number.',
        triggers: ['missing number', 'find the missing', '0 to n range', 'one number missing'],
        dataStructure: 'Array (in-place)',
        approach: 'Cyclic sort. Scan for arr[i] != i+1. That i+1 is missing.',
        example: 'Find missing number in [0..n] → after sort, first mismatch is answer',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Find Duplicate Number',
        description: 'Array has values 1..n, one value appears twice. Find it.',
        triggers: ['find duplicate', 'one duplicate', 'array 1 to n with one repeat'],
        dataStructure: 'Array (in-place)',
        approach: 'Cyclic sort. When arr[i] == arr[arr[i]-1] and they differ → arr[i] is duplicate.',
        example: 'Find duplicate in [1..n] array → skip when target slot already has correct value',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
    ],
  },
  {
    id: 'dfs', name: 'DFS', icon: '🌲', color: '#22c55e',
    types: [
      {
        name: 'Tree DFS (Path Problems)',
        description: 'Explore all root-to-leaf paths, track path sum or sequence.',
        triggers: ['path sum', 'root to leaf', 'all paths', 'path with target', 'path equals'],
        dataStructure: 'Recursive call stack (implicit) or explicit stack',
        approach: 'Pass running sum/path to children. At leaf: check condition. Backtrack after.',
        example: 'Path Sum II → collect all paths that equal target',
        complexity: { time: 'O(n)', space: 'O(h)' },
      },
      {
        name: 'Graph DFS (Islands / Components)',
        description: 'Visit all cells connected to a starting cell. Mark visited.',
        triggers: ['number of islands', 'connected components', 'flood fill', 'count regions', 'number of provinces'],
        dataStructure: 'Grid / adjacency list + visited set',
        approach: 'For each unvisited cell: DFS to mark entire component. Count DFS calls.',
        example: 'Number of Islands → DFS/BFS from each "1", mark visited',
        complexity: { time: 'O(m*n)', space: 'O(m*n)' },
      },
      {
        name: 'Backtracking DFS',
        description: 'Explore all possibilities, undo choices when backtracking.',
        triggers: ['generate all', 'all permutations', 'all combinations', 'all subsets', 'n-queens', 'sudoku'],
        dataStructure: 'Recursion + mutable path (backtrack on return)',
        approach: 'For each choice: make choice, recurse, undo choice. Prune invalid branches early.',
        example: 'Generate all permutations → swap/unsawp at each level',
        complexity: { time: 'O(n! or 2^n)', space: 'O(n)' },
      },
      {
        name: 'DFS with Memoization (Recursive DP)',
        description: 'DFS with cache to avoid recomputing subproblems.',
        triggers: ['word break', 'decode ways', 'unique paths', 'count ways top-down'],
        dataStructure: 'HashMap / array for memo',
        approach: 'DFS(state). If state in memo → return. Compute, store, return.',
        example: 'Word Break → DFS from index i, memo[i] = can break from i',
        complexity: { time: 'O(n²) typical', space: 'O(n)' },
      },
    ],
  },
  {
    id: 'bfs', name: 'BFS', icon: '🌊', color: '#3b82f6',
    types: [
      {
        name: 'Level-Order BFS',
        description: 'Process tree level by level. Use queue, track level boundaries.',
        triggers: ['level order', 'level by level', 'zigzag', 'right side view', 'cousins'],
        dataStructure: 'Queue (deque)',
        approach: 'Add root. While queue non-empty: process all of current level (size = queue.length). Add children.',
        example: 'Binary Tree Level Order Traversal → snapshot queue size each level',
        complexity: { time: 'O(n)', space: 'O(w) w=max width' },
      },
      {
        name: 'Shortest Path BFS (Unweighted)',
        description: 'BFS guarantees shortest path in unweighted graphs. Count levels = distance.',
        triggers: ['shortest path', 'minimum steps', 'minimum moves', 'least number', 'word ladder'],
        dataStructure: 'Queue + visited set',
        approach: 'BFS from source. Each level = 1 step. Return level when target reached.',
        example: 'Word Ladder → BFS where each word is a node, edge = 1 char change',
        complexity: { time: 'O(V+E)', space: 'O(V)' },
      },
      {
        name: 'Multi-Source BFS',
        description: 'BFS from multiple starting points simultaneously.',
        triggers: ['rotting oranges', 'nearest 0', 'distance to nearest', 'spreading from multiple sources'],
        dataStructure: 'Queue (pre-loaded with all sources)',
        approach: 'Add all sources to queue at start. BFS outward. Distance tracked per cell.',
        example: 'Rotting Oranges → start BFS from all rotten oranges at once',
        complexity: { time: 'O(m*n)', space: 'O(m*n)' },
      },
    ],
  },
  {
    id: 'topological-sort', name: 'Topological Sort', icon: '📊', color: '#f97316',
    types: [
      {
        name: 'Kahn\'s Algorithm (BFS-based)',
        description: 'Process nodes with in-degree 0 first. Decrement neighbors.',
        triggers: ['course schedule', 'prerequisites', 'task order', 'build order', 'dependency'],
        dataStructure: 'Queue + in-degree array',
        approach: 'Build graph + in-degree. Queue all 0-degree nodes. Process → decrement neighbors → add new 0s.',
        example: 'Course Schedule → can all courses finish? → cycle detection via topo sort',
        complexity: { time: 'O(V+E)', space: 'O(V+E)' },
      },
      {
        name: 'DFS-based Topological Sort',
        description: 'Post-order DFS. Add to result AFTER visiting all children.',
        triggers: ['alien dictionary', 'sequence reconstruction', 'ordering from comparisons'],
        dataStructure: 'Stack + visited set + recursion stack (cycle)',
        approach: 'DFS. After all neighbors visited → push to stack. Reverse stack = order.',
        example: 'Alien Dictionary → build char order graph, DFS post-order',
        complexity: { time: 'O(V+E)', space: 'O(V+E)' },
      },
      {
        name: 'Cycle Detection in Directed Graph',
        description: 'Use topo sort: if result length < n → cycle exists.',
        triggers: ['detect cycle directed', 'can all tasks complete', 'is schedule possible'],
        dataStructure: 'In-degree array or DFS with colors (white/gray/black)',
        approach: "Kahn's: if processed count < n → cycle. DFS: gray node in stack → cycle.",
        example: 'Course Schedule (can finish all) → cycle in prerequisite graph?',
        complexity: { time: 'O(V+E)', space: 'O(V)' },
      },
    ],
  },
  {
    id: 'heap-priority-queue', name: 'Heap / Priority Queue', icon: '🏔️', color: '#a855f7',
    types: [
      {
        name: 'Top K Elements',
        description: 'Find k largest or k smallest elements without full sort.',
        triggers: ['k largest', 'k smallest', 'top k', 'kth largest', 'kth smallest', 'k most frequent'],
        dataStructure: 'Min-heap of size k (for k largest) or Max-heap',
        approach: 'For k largest: min-heap size k. If new > heap.top → pop, push. Result = heap contents.',
        example: 'K Closest Points → min-heap on distance, keep k elements',
        complexity: { time: 'O(n log k)', space: 'O(k)' },
      },
      {
        name: 'Running Median / Two Heaps',
        description: 'Maintain median dynamically. Max-heap for lower half, min-heap for upper.',
        triggers: ['running median', 'median of stream', 'find median', 'sliding window median'],
        dataStructure: 'Max-heap (lower) + Min-heap (upper)',
        approach: 'Add to max-heap. Rebalance if sizes differ. Median = top of larger or avg of both tops.',
        example: 'Find Median from Data Stream → two heaps trick',
        complexity: { time: 'O(log n) per add', space: 'O(n)' },
      },
      {
        name: 'K-way Merge',
        description: 'Merge k sorted lists/arrays efficiently.',
        triggers: ['merge k sorted', 'k sorted lists', 'smallest from k lists', 'kth in matrix'],
        dataStructure: 'Min-heap with (value, list_idx, element_idx)',
        approach: 'Init heap with first element of each list. Pop min → push next from same list.',
        example: 'Merge K Sorted Lists → heap always gives next smallest',
        complexity: { time: 'O(n log k)', space: 'O(k)' },
      },
    ],
  },
  {
    id: 'subsets-backtracking', name: 'Subsets / Backtracking', icon: '🎯', color: '#ef4444',
    types: [
      {
        name: 'Subsets (Power Set)',
        description: 'Generate all 2^n subsets. Include or exclude each element.',
        triggers: ['all subsets', 'power set', 'all combinations', 'subset sum'],
        dataStructure: 'Recursion + result array',
        approach: 'At each index: 1) include arr[i], recurse, 2) exclude, recurse. Base: add current path.',
        example: 'Subsets → binary choice at each element',
        complexity: { time: 'O(2^n)', space: 'O(n)' },
      },
      {
        name: 'Permutations',
        description: 'Generate all n! arrangements of elements.',
        triggers: ['all permutations', 'all arrangements', 'letter combinations', 'permutation of'],
        dataStructure: 'Recursion + used[] array or swap-based',
        approach: 'Swap arr[i] with arr[start], recurse, swap back. Or: pick unused element each time.',
        example: 'Permutations → fix position by position, branch on remaining',
        complexity: { time: 'O(n!)', space: 'O(n)' },
      },
      {
        name: 'Combinations (k-size)',
        description: 'Choose k elements from n without repetition.',
        triggers: ['combinations', 'choose k', 'k numbers from 1 to n', 'combination sum'],
        dataStructure: 'Recursion with start index (no revisit)',
        approach: 'For i from start to n: include i, recurse(i+1), backtrack. Stop when len=k.',
        example: 'Combination Sum → pick elements, allow reuse until sum reached',
        complexity: { time: 'O(C(n,k))', space: 'O(k)' },
      },
      {
        name: 'Constraint Satisfaction (N-Queens, Sudoku)',
        description: 'Place elements with hard constraints. Prune early.',
        triggers: ['n queens', 'sudoku solver', 'place without conflict', 'valid placement'],
        dataStructure: 'Board + sets (cols, diagonals)',
        approach: 'Try each position. Check constraints. If valid → place, recurse, remove (backtrack).',
        example: 'N-Queens → place queen row by row, track attacked columns/diagonals',
        complexity: { time: 'O(n!)', space: 'O(n)' },
      },
    ],
  },
  {
    id: 'dynamic-programming', name: 'Dynamic Programming', icon: '🧠', color: '#6366f1',
    types: [
      {
        name: '1D DP (Linear)',
        description: 'Each state depends on a few previous states in a 1D array.',
        triggers: ['climbing stairs', 'fibonacci', 'house robber', 'min cost', 'jump game', 'decode ways'],
        dataStructure: 'dp[] array or 2 variables',
        approach: 'dp[i] = f(dp[i-1], dp[i-2], ...). Fill left to right. Often optimize to O(1) space.',
        example: 'House Robber → dp[i] = max(dp[i-1], dp[i-2] + arr[i])',
        complexity: { time: 'O(n)', space: 'O(1) with optimization' },
      },
      {
        name: '2D DP (Grid/Two Sequences)',
        description: 'State is a 2D table. Common for grid paths or comparing two sequences.',
        triggers: ['unique paths', 'minimum path sum', 'LCS', 'edit distance', 'coin change 2', 'matrix chain'],
        dataStructure: 'dp[][] 2D array',
        approach: 'dp[i][j] = f(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]). Fill row by row.',
        example: 'Edit Distance → dp[i][j] = min ops to match s1[0..i] and s2[0..j]',
        complexity: { time: 'O(m*n)', space: 'O(m*n) or O(n)' },
      },
      {
        name: '0/1 Knapsack',
        description: 'Each item used at most once. Include or exclude.',
        triggers: ['0/1 knapsack', 'subset sum', 'partition equal subset', 'target sum', 'can reach sum'],
        dataStructure: 'dp[capacity] 1D or dp[n][capacity] 2D',
        approach: 'dp[j] = max(dp[j], dp[j-w]+v). Iterate items outer, capacity inner (right to left).',
        example: 'Partition Equal Subset Sum → can we pick elements summing to total/2?',
        complexity: { time: 'O(n * W)', space: 'O(W)' },
      },
      {
        name: 'Unbounded Knapsack',
        description: 'Items can be used unlimited times.',
        triggers: ['coin change', 'unbounded knapsack', 'complete knapsack', 'rod cutting', 'repetition allowed'],
        dataStructure: 'dp[amount] 1D',
        approach: 'dp[j] = min/max(dp[j], dp[j-coin]+1). Iterate capacity left to right (allows reuse).',
        example: 'Coin Change → dp[amount] = min coins needed, can reuse coins',
        complexity: { time: 'O(n * W)', space: 'O(W)' },
      },
      {
        name: 'Interval DP',
        description: 'Problem defined over a range [i,j]. Build from smaller intervals.',
        triggers: ['burst balloons', 'matrix chain multiplication', 'palindrome partitioning', 'stone game'],
        dataStructure: 'dp[i][j] where j > i',
        approach: 'Fill by length: for len=2..n, for all i: j=i+len-1. dp[i][j]=f(dp[i][k], dp[k+1][j]).',
        example: 'Burst Balloons → dp[i][j] = max coins from bursting all between i and j',
        complexity: { time: 'O(n³)', space: 'O(n²)' },
      },
    ],
  },
  {
    id: 'bit-manipulation', name: 'Bit Manipulation', icon: '🔢', color: '#64748b',
    types: [
      {
        name: 'XOR Tricks',
        description: 'XOR of same elements = 0. XOR of all with extras finds unique.',
        triggers: ['single number', 'find unique', 'non-repeating', 'XOR pairs'],
        dataStructure: 'Single integer variable',
        approach: 'XOR all elements. Repeated elements cancel. Unique element remains.',
        example: 'Single Number → a^a=0, 0^b=b → XOR all gives unique',
        complexity: { time: 'O(n)', space: 'O(1)' },
      },
      {
        name: 'Bit Masking',
        description: 'Use integer bits to represent a set. State compression for subsets.',
        triggers: ['bitmask DP', 'subset using bits', 'visited states as bit', 'TSP', 'assignment problem'],
        dataStructure: 'Integer as bitmask',
        approach: 'Set bit: mask | (1<<i). Check bit: mask & (1<<i). Clear bit: mask & ~(1<<i).',
        example: 'TSP → dp[mask][city] = min cost visiting cities in mask ending at city',
        complexity: { time: 'O(2^n * n)', space: 'O(2^n)' },
      },
      {
        name: 'Bit Counting / Powers',
        description: 'Count set bits, check power of 2, find highest set bit.',
        triggers: ['count bits', 'number of 1 bits', 'power of 2', 'hamming weight', 'popcount'],
        dataStructure: 'Integer arithmetic',
        approach: 'Power of 2: n & (n-1) == 0. Count bits: n & (n-1) removes lowest bit. Brian Kernighan.',
        example: 'Number of 1 Bits → while n: count += n&1, n>>=1',
        complexity: { time: 'O(log n)', space: 'O(1)' },
      },
    ],
  },
  {
    id: 'trie', name: 'Trie', icon: '🌐', color: '#0ea5e9',
    types: [
      {
        name: 'Basic Trie (Insert/Search/Prefix)',
        description: 'Tree of characters. Each path = word/prefix.',
        triggers: ['autocomplete', 'starts with', 'prefix search', 'word exists', 'dictionary search'],
        dataStructure: 'TrieNode { children: Map/array, isEnd: bool }',
        approach: 'Insert: walk char by char, create nodes. Search: walk, check isEnd. Prefix: walk, no isEnd check.',
        example: 'Implement Trie → insert/search/startsWith',
        complexity: { time: 'O(m) per op (m=word length)', space: 'O(n*m)' },
      },
      {
        name: 'Word Search with Trie',
        description: 'Search multiple words in grid simultaneously using trie.',
        triggers: ['word search II', 'find all words in grid', 'search multiple words'],
        dataStructure: 'Trie + DFS on grid',
        approach: 'Build trie from words. DFS on grid, follow trie simultaneously. Collect complete words.',
        example: 'Word Search II → trie prunes branches early vs checking each word separately',
        complexity: { time: 'O(m*n*4^L)', space: 'O(total chars)' },
      },
    ],
  },
  {
    id: 'graph-algorithms', name: 'Graph Algorithms', icon: '🕸️', color: '#84cc16',
    types: [
      {
        name: 'Union-Find (Disjoint Set)',
        description: 'Group elements into connected components. Efficient merge and find.',
        triggers: ['connected components', 'same group', 'union find', 'redundant connection', 'number of connected', 'accounts merge'],
        dataStructure: 'parent[] + rank[] arrays',
        approach: 'find(x): path compress. union(x,y): merge by rank. Same root = same component.',
        example: 'Number of Connected Components → union edges, count distinct roots',
        complexity: { time: 'O(α(n)) per op', space: 'O(n)' },
      },
      {
        name: 'Dijkstra (Shortest Path Weighted)',
        description: 'Find shortest path in weighted graph with non-negative weights.',
        triggers: ['shortest path weighted', 'minimum cost path', 'cheapest flight', 'network delay'],
        dataStructure: 'Min-heap (dist, node) + dist[] array',
        approach: 'Heap: (0, src). Pop min dist node. For each neighbor: relax edge. Push if improved.',
        example: 'Network Delay Time → Dijkstra, return max dist to any node',
        complexity: { time: 'O((V+E) log V)', space: 'O(V+E)' },
      },
      {
        name: 'Minimum Spanning Tree',
        description: 'Connect all nodes with minimum total edge weight.',
        triggers: ['minimum spanning tree', 'minimum cost to connect', 'min cost cable', 'Kruskal', 'Prim'],
        dataStructure: 'Sorted edges + Union-Find (Kruskal) or heap (Prim)',
        approach: "Kruskal: sort edges, add smallest that doesn't form cycle (Union-Find). Prim: greedy from any node.",
        example: 'Min Cost to Connect All Points → Prim/Kruskal on point distances',
        complexity: { time: 'O(E log E)', space: 'O(V)' },
      },
    ],
  },
];

export function getPatternTypes(patternId: string): PatternWithTypes | null {
  return PATTERN_TYPES.find(p => p.id === patternId) ?? null;
}
