// ================================================================
// PATTERN RECOGNITION CHALLENGES
// Each entry: read the problem description → identify pattern + type + DS
// ================================================================

export interface RecognitionChallenge {
  id       : number;
  title    : string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  // What the user sees:
  inputDesc   : string;  // what is the input?
  outputDesc  : string;  // what should be returned?
  constraints : string[];
  keywords    : string[]; // highlighted keywords
  // Answer:
  correctPattern  : string; // pattern id
  correctType     : string; // pattern type name
  correctDS       : string; // data structure
  whyThisPattern  : string; // explanation
  keyTriggers     : string[]; // which words in problem gave it away
  approach        : string;  // one-line approach
  timeComplexity  : string;
}

export const RECOGNITION_CHALLENGES: RecognitionChallenge[] = [
  // ─── Sliding Window ───
  {
    id: 1, title: 'Max Sum Subarray of Size K', difficulty: 'Easy',
    inputDesc: 'Integer array nums, integer k',
    outputDesc: 'Maximum sum of any contiguous subarray of size k',
    constraints: ['1 ≤ k ≤ nums.length ≤ 10⁵', 'Values can be negative'],
    keywords: ['contiguous subarray', 'size k', 'maximum sum'],
    correctPattern: 'sliding-window', correctType: 'Fixed-Size Window',
    correctDS: 'Array + running sum variable',
    whyThisPattern: '"Contiguous subarray of fixed size k" is the classic fixed sliding window signal. You slide a window of exactly k elements.',
    keyTriggers: ['contiguous subarray', 'size k'],
    approach: 'Init sum of first k. Slide: add arr[i], subtract arr[i-k]. Track max.',
    timeComplexity: 'O(n)',
  },
  {
    id: 2, title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium',
    inputDesc: 'String s',
    outputDesc: 'Length of the longest substring with all unique characters',
    constraints: ['0 ≤ s.length ≤ 5×10⁴', 's has English letters, digits, symbols'],
    keywords: ['longest substring', 'without repeating', 'unique characters'],
    correctPattern: 'sliding-window', correctType: 'Variable-Size Window (At Most K)',
    correctDS: 'HashMap (char → last index) + two pointers',
    whyThisPattern: '"Longest substring" + constraint on characters = variable window. Expand right, shrink left when duplicate found.',
    keyTriggers: ['longest substring', 'without repeating'],
    approach: 'l=0, set. For each r: if s[r] in set → shrink l. Add s[r], track max (r-l+1).',
    timeComplexity: 'O(n)',
  },
  {
    id: 3, title: 'Fruit Into Baskets', difficulty: 'Medium',
    inputDesc: 'Array fruits[] where fruits[i] is the type of fruit at tree i',
    outputDesc: 'Max trees you can pick from (starting any tree, at most 2 types)',
    constraints: ['Must pick consecutive trees', 'Can hold at most 2 types of fruit'],
    keywords: ['consecutive', 'at most 2 types', 'maximum subarray', 'longest'],
    correctPattern: 'sliding-window', correctType: 'Variable-Size Window (At Most K)',
    correctDS: 'HashMap (fruit→count) + two pointers',
    whyThisPattern: '"Consecutive trees" + "at most 2 types" = longest subarray with at most 2 distinct values. Classic variable window.',
    keyTriggers: ['consecutive', 'at most 2 types'],
    approach: 'HashMap of fruit counts. Expand r. When map size > 2 → shrink l. Track max window.',
    timeComplexity: 'O(n)',
  },
  {
    id: 4, title: 'Sliding Window Maximum', difficulty: 'Hard',
    inputDesc: 'Integer array nums, window size k',
    outputDesc: 'Array of maximum values in each window of size k',
    constraints: ['1 ≤ k ≤ nums.length ≤ 10⁵', 'Need max of EACH window'],
    keywords: ['sliding window', 'maximum', 'each window of size k'],
    correctPattern: 'sliding-window', correctType: 'Sliding Window with Deque (Min/Max)',
    correctDS: 'Monotonic decreasing deque (stores indices)',
    whyThisPattern: '"Maximum in each window" requires O(n) solution. Naive O(nk) too slow. Monotonic deque gives O(n).',
    keyTriggers: ['maximum in each window', 'all windows'],
    approach: 'Deque stores indices in decreasing order. Front = max. Remove stale indices. Append max when window full.',
    timeComplexity: 'O(n)',
  },
  // ─── Two Pointers ───
  {
    id: 5, title: 'Two Sum II (Sorted Input)', difficulty: 'Easy',
    inputDesc: 'Sorted (ascending) integer array numbers, integer target',
    outputDesc: '1-indexed positions of two numbers that sum to target',
    constraints: ['Sorted in non-decreasing order', 'Exactly one solution', 'Cannot use same element twice'],
    keywords: ['sorted array', 'two numbers', 'sum to target', 'one solution'],
    correctPattern: 'two-pointers', correctType: 'Opposite Ends (Converging)',
    correctDS: 'Sorted array + two pointers (no extra space)',
    whyThisPattern: '"Sorted array" + "pair that sums to target" = classic opposite-end two pointers. No need for hashmap.',
    keyTriggers: ['sorted', 'two numbers that sum to'],
    approach: 'l=0, r=n-1. If sum < target → l++. If sum > target → r--. If equal → return.',
    timeComplexity: 'O(n)',
  },
  {
    id: 6, title: 'Container With Most Water', difficulty: 'Medium',
    inputDesc: 'Array height[] where height[i] is the height of a vertical line at i',
    outputDesc: 'Maximum amount of water a container formed by two lines can hold',
    constraints: ['Water = min(height[l], height[r]) * (r - l)', 'Find maximum over all pairs'],
    keywords: ['two lines', 'maximum water', 'container', 'area between'],
    correctPattern: 'two-pointers', correctType: 'Opposite Ends (Converging)',
    correctDS: 'Array + two pointers',
    whyThisPattern: 'Maximize area. Moving the shorter bar inward can only help. Greedy: always move the smaller height pointer.',
    keyTriggers: ['maximum water', 'two lines', 'area'],
    approach: 'l=0, r=n-1. area=min(h[l],h[r])*(r-l). Move smaller pointer inward. Track max.',
    timeComplexity: 'O(n)',
  },
  {
    id: 7, title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy',
    inputDesc: 'Sorted integer array nums (non-decreasing)',
    outputDesc: 'Count of unique elements (modify in-place, unique elements at front)',
    constraints: ['Sorted array', 'In-place modification required', 'O(1) extra space'],
    keywords: ['sorted', 'in-place', 'remove duplicates', 'unique elements'],
    correctPattern: 'two-pointers', correctType: 'Same Direction (Fast-Read)',
    correctDS: 'Array (in-place) + slow/fast pointers',
    whyThisPattern: '"In-place", "remove duplicates" from sorted array = fast-slow same-direction pointers. Slow = write head.',
    keyTriggers: ['in-place', 'remove duplicates', 'sorted'],
    approach: 'slow=1. For fast from 1: if nums[fast]!=nums[fast-1] → nums[slow++]=nums[fast].',
    timeComplexity: 'O(n)',
  },
  {
    id: 8, title: '3Sum', difficulty: 'Medium',
    inputDesc: 'Integer array nums',
    outputDesc: 'All unique triplets [nums[i], nums[j], nums[k]] such that i≠j≠k and sum=0',
    constraints: ['No duplicate triplets', '0 ≤ nums.length ≤ 3000'],
    keywords: ['triplets', 'sum equals zero', 'unique triplets', 'three numbers'],
    correctPattern: 'two-pointers', correctType: 'Three Pointers / Multi-Pass',
    correctDS: 'Sorted array + nested two-pointer',
    whyThisPattern: '"Triplets summing to 0" = 3Sum pattern. Sort + fix first element + two-pointer for the remaining sum.',
    keyTriggers: ['triplets', 'three numbers', 'sum = 0'],
    approach: 'Sort. For each i: two-pointer on [i+1, n-1] for -nums[i]. Skip duplicates.',
    timeComplexity: 'O(n²)',
  },
  // ─── Binary Search ───
  {
    id: 9, title: 'Binary Search', difficulty: 'Easy',
    inputDesc: 'Sorted array nums, target integer',
    outputDesc: 'Index of target, or -1 if not found',
    constraints: ['Sorted in ascending order', 'All distinct values', 'Must be O(log n)'],
    keywords: ['sorted array', 'search', 'target', 'O(log n)', 'find index'],
    correctPattern: 'binary-search', correctType: 'Classic Search in Sorted Array',
    correctDS: 'Sorted array + lo/hi pointers',
    whyThisPattern: '"Sorted array + find target + O(log n)" = textbook binary search.',
    keyTriggers: ['sorted', 'O(log n)', 'search target'],
    approach: 'lo=0, hi=n-1. mid=(lo+hi)//2. Compare, adjust lo/hi.',
    timeComplexity: 'O(log n)',
  },
  {
    id: 10, title: 'Koko Eating Bananas', difficulty: 'Medium',
    inputDesc: 'Array piles[] (bananas per pile), integer h (total hours)',
    outputDesc: 'Minimum eating speed k such that Koko can eat all bananas within h hours',
    constraints: ['k bananas per hour', 'For each pile: takes ceil(piles[i]/k) hours', 'Find minimum valid k'],
    keywords: ['minimum speed', 'within h hours', 'minimize k', 'feasibility', 'find minimum k'],
    correctPattern: 'binary-search', correctType: 'Binary Search on Answer Space',
    correctDS: 'Custom canFinish(k) function + binary search on range [1, max(piles)]',
    whyThisPattern: '"Find minimum k" where the condition is monotonic = binary search on ANSWER. Not searching array.',
    keyTriggers: ['minimum speed', 'minimum k', 'feasibility check'],
    approach: 'canFinish(k)=sum(ceil(p/k)) ≤ h. Binary search on k from 1 to max(piles).',
    timeComplexity: 'O(n log(max))',
  },
  {
    id: 11, title: 'Find First and Last Position', difficulty: 'Medium',
    inputDesc: 'Sorted array nums, target integer',
    outputDesc: 'Starting and ending position of target, or [-1,-1] if not found',
    constraints: ['Sorted ascending', 'May have duplicates', 'Must be O(log n)'],
    keywords: ['first occurrence', 'last occurrence', 'range', 'sorted with duplicates'],
    correctPattern: 'binary-search', correctType: 'Find First/Last Occurrence',
    correctDS: 'Two binary searches (one for left bound, one for right)',
    whyThisPattern: '"First and last position" in sorted array = two binary searches. Leftmost: keep searching left when found.',
    keyTriggers: ['first occurrence', 'last occurrence', 'starting and ending position'],
    approach: 'leftBS: when found, hi=mid-1. rightBS: when found, lo=mid+1.',
    timeComplexity: 'O(log n)',
  },
  // ─── Heap ───
  {
    id: 12, title: 'K Largest Elements', difficulty: 'Easy',
    inputDesc: 'Unsorted array nums, integer k',
    outputDesc: 'The k largest elements in the array',
    constraints: ['1 ≤ k ≤ nums.length', 'Return in any order'],
    keywords: ['k largest', 'top k', 'k elements'],
    correctPattern: 'heap-priority-queue', correctType: 'Top K Elements',
    correctDS: 'Min-heap of size k',
    whyThisPattern: '"k largest" = min-heap of size k. New element > heap.min? → replace. Heap stores the k largest seen.',
    keyTriggers: ['k largest', 'top k'],
    approach: 'Min-heap size k. For each element: if > heap.top → pop, push. Return heap.',
    timeComplexity: 'O(n log k)',
  },
  {
    id: 13, title: 'Find Median from Data Stream', difficulty: 'Hard',
    inputDesc: 'Stream of integers added one by one',
    outputDesc: 'After each addNum, return current median of all numbers so far',
    constraints: ['Dynamic addition', 'Median after every insert', '-10⁵ ≤ val ≤ 10⁵'],
    keywords: ['median', 'data stream', 'running median', 'dynamic'],
    correctPattern: 'heap-priority-queue', correctType: 'Running Median / Two Heaps',
    correctDS: 'Max-heap (lower half) + Min-heap (upper half)',
    whyThisPattern: '"Running median" requires constant access to middle elements. Two heaps: max-heap for lower, min-heap for upper half.',
    keyTriggers: ['median', 'stream', 'running'],
    approach: 'Lower=max-heap, upper=min-heap. Rebalance sizes. Median=top of larger or avg of tops.',
    timeComplexity: 'O(log n) per add, O(1) per findMedian',
  },
  {
    id: 14, title: 'Merge K Sorted Lists', difficulty: 'Hard',
    inputDesc: 'Array of k linked lists, each sorted in ascending order',
    outputDesc: 'Single merged sorted linked list',
    constraints: ['k linked lists', 'Each list sorted', '0 ≤ total nodes ≤ 10⁴'],
    keywords: ['k sorted lists', 'merge', 'combine sorted'],
    correctPattern: 'heap-priority-queue', correctType: 'K-way Merge',
    correctDS: 'Min-heap storing (value, list_idx, node)',
    whyThisPattern: '"Merge k sorted lists" = k-way merge with heap. Always extract global minimum efficiently.',
    keyTriggers: ['k sorted lists', 'merge', 'k lists'],
    approach: 'Init heap with head of each list. Pop min → add to result → push next node from same list.',
    timeComplexity: 'O(n log k)',
  },
  // ─── DFS ───
  {
    id: 15, title: 'Number of Islands', difficulty: 'Medium',
    inputDesc: '2D binary grid (\'1\'=land, \'0\'=water)',
    outputDesc: 'Number of islands (connected groups of \'1\')',
    constraints: ['m×n grid', 'Connected horizontally or vertically', '1 ≤ m,n ≤ 300'],
    keywords: ['grid', 'connected', 'islands', 'groups of 1s', 'count regions'],
    correctPattern: 'dfs', correctType: 'Graph DFS (Islands / Components)',
    correctDS: 'Grid + visited marking (or modify in-place)',
    whyThisPattern: '"Count connected groups" in a grid = flood fill with DFS/BFS. Each DFS from unvisited \'1\' = one island.',
    keyTriggers: ['islands', 'connected', 'count regions'],
    approach: 'For each unvisited \'1\': DFS to mark whole island as visited. Count DFS calls.',
    timeComplexity: 'O(m*n)',
  },
  {
    id: 16, title: 'All Root-to-Leaf Paths', difficulty: 'Medium',
    inputDesc: 'Binary tree root, integer targetSum',
    outputDesc: 'All root-to-leaf paths where path sum equals targetSum',
    constraints: ['Binary tree', 'Must include ALL paths', 'Not just count'],
    keywords: ['all paths', 'root to leaf', 'path sum equals', 'target'],
    correctPattern: 'dfs', correctType: 'Tree DFS (Path Problems)',
    correctDS: 'Recursion + current path array (backtrack)',
    whyThisPattern: '"All paths" + "root to leaf" + "path sum" = DFS with backtracking. Track running sum and path.',
    keyTriggers: ['all paths', 'root to leaf', 'path sum'],
    approach: 'DFS(node, remaining, path). At leaf: if remaining==0 → save path. Backtrack by popping path.',
    timeComplexity: 'O(n²) worst case (copying paths)',
  },
  {
    id: 17, title: 'Generate All Permutations', difficulty: 'Medium',
    inputDesc: 'Array nums with distinct integers',
    outputDesc: 'All possible permutations',
    constraints: ['All unique elements', 'Return all n! arrangements', '1 ≤ nums.length ≤ 6'],
    keywords: ['all permutations', 'all arrangements', 'generate all', 'every ordering'],
    correctPattern: 'subsets-backtracking', correctType: 'Permutations',
    correctDS: 'Recursion + used[] array or swap-based',
    whyThisPattern: '"All permutations" = backtracking. At each position, try each unused element.',
    keyTriggers: ['all permutations', 'all arrangements', 'generate all'],
    approach: 'Fix position by position. Try each unused num. Recurse. Undo (backtrack).',
    timeComplexity: 'O(n! × n)',
  },
  {
    id: 18, title: 'Combination Sum', difficulty: 'Medium',
    inputDesc: 'Array candidates (distinct), target integer',
    outputDesc: 'All unique combinations that sum to target (can reuse elements)',
    constraints: ['Can reuse same element', 'Number of combos guaranteed < 150', 'candidates[i] > 0'],
    keywords: ['combinations', 'sum to target', 'reuse elements', 'all combinations'],
    correctPattern: 'subsets-backtracking', correctType: 'Combinations (k-size)',
    correctDS: 'Recursion with start index (allow same index for reuse)',
    whyThisPattern: '"All combinations summing to target" + "can reuse" = backtracking with same-index recursion.',
    keyTriggers: ['all combinations', 'sum to target', 'combinations that sum'],
    approach: 'DFS(start, remaining, path). For i from start: pick candidates[i], recurse(i, remaining-c[i]).',
    timeComplexity: 'O(2^(t/m)) where t=target, m=min candidate',
  },
  // ─── BFS ───
  {
    id: 19, title: 'Binary Tree Level Order Traversal', difficulty: 'Medium',
    inputDesc: 'Binary tree root',
    outputDesc: 'Nodes grouped by level [[level0], [level1], ...]',
    constraints: ['Group by level', '0 ≤ nodes ≤ 2000'],
    keywords: ['level order', 'level by level', 'grouped by depth', 'breadth first'],
    correctPattern: 'bfs', correctType: 'Level-Order BFS',
    correctDS: 'Queue (deque)',
    whyThisPattern: '"Level order" / "level by level" = BFS. Queue processes nodes width-first.',
    keyTriggers: ['level order', 'level by level'],
    approach: 'Queue with root. Each iteration: snapshot size, process that many nodes, add children.',
    timeComplexity: 'O(n)',
  },
  {
    id: 20, title: 'Word Ladder', difficulty: 'Hard',
    inputDesc: 'beginWord, endWord, wordList',
    outputDesc: 'Minimum number of word transformations to reach endWord (change 1 char at a time)',
    constraints: ['Each word must be in wordList', 'Change exactly 1 char per step', 'Find shortest path'],
    keywords: ['shortest transformation', 'minimum steps', 'one character at a time', 'word to word'],
    correctPattern: 'bfs', correctType: 'Shortest Path BFS (Unweighted)',
    correctDS: 'Queue + visited set (words)',
    whyThisPattern: '"Minimum steps" in transformation = unweighted shortest path = BFS. Each word = node, 1-char-change = edge.',
    keyTriggers: ['minimum steps', 'shortest path', 'minimum transformation'],
    approach: 'BFS from beginWord. For each word: try all 26*len neighbors. If in wordList and unvisited → enqueue.',
    timeComplexity: 'O(n × m × 26) where n=wordList size, m=word length',
  },
  {
    id: 21, title: 'Rotting Oranges', difficulty: 'Medium',
    inputDesc: '2D grid: 0=empty, 1=fresh, 2=rotten',
    outputDesc: 'Minimum minutes until no fresh orange left (-1 if impossible)',
    constraints: ['Rotten orange infects all adjacent fresh in 1 minute', 'Simultaneous spread'],
    keywords: ['rotten spreads', 'minimum minutes', 'simultaneous', 'multi-source', 'infect adjacent'],
    correctPattern: 'bfs', correctType: 'Multi-Source BFS',
    correctDS: 'Queue pre-loaded with all rotten oranges',
    whyThisPattern: '"Simultaneous spread from multiple sources" = multi-source BFS. Start from ALL rotten at once.',
    keyTriggers: ['simultaneous', 'all rotten spread at same time', 'minimum time'],
    approach: 'Add all rotten to queue. BFS outward. Count levels = minutes. Check fresh remain.',
    timeComplexity: 'O(m*n)',
  },
  // ─── Topological Sort ───
  {
    id: 22, title: 'Course Schedule', difficulty: 'Medium',
    inputDesc: 'numCourses, prerequisites[][2] (each [a,b] means b must be taken before a)',
    outputDesc: 'True if you can finish all courses, false if there\'s a cycle',
    constraints: ['0 ≤ prerequisites.length ≤ 5000', 'Courses numbered 0 to n-1'],
    keywords: ['prerequisites', 'course before another', 'can finish', 'cycle detection', 'dependency'],
    correctPattern: 'topological-sort', correctType: 'Cycle Detection in Directed Graph',
    correctDS: 'Adjacency list + in-degree array + queue',
    whyThisPattern: '"Prerequisites" + "can all finish" = directed graph cycle detection via topological sort.',
    keyTriggers: ['prerequisites', 'can finish', 'dependency'],
    approach: "Kahn's BFS. If topological order contains all n courses → no cycle → return true.",
    timeComplexity: 'O(V+E)',
  },
  {
    id: 23, title: 'Course Schedule II (Find Order)', difficulty: 'Medium',
    inputDesc: 'numCourses, prerequisites[][2]',
    outputDesc: 'Valid ordering of courses to take all (empty array if impossible)',
    constraints: ['Return one valid order', 'Return [] if cycle exists'],
    keywords: ['valid order', 'course order', 'dependency order', 'prerequisites'],
    correctPattern: 'topological-sort', correctType: 'Kahn\'s Algorithm (BFS-based)',
    correctDS: 'Queue + in-degree array + adjacency list',
    whyThisPattern: '"Valid ordering with dependencies" = topological sort. Kahn\'s gives order directly.',
    keyTriggers: ['valid order', 'ordering', 'prerequisites'],
    approach: "Build graph + in-degree. Queue 0-in-degree nodes. Process → decrement → add new 0s → order.",
    timeComplexity: 'O(V+E)',
  },
  // ─── DP ───
  {
    id: 24, title: 'Climbing Stairs', difficulty: 'Easy',
    inputDesc: 'Integer n (number of stairs)',
    outputDesc: 'Number of distinct ways to climb n stairs (1 or 2 steps at a time)',
    constraints: ['1 ≤ n ≤ 45', '1 or 2 steps per move'],
    keywords: ['number of ways', 'distinct ways', '1 or 2 steps', 'count paths'],
    correctPattern: 'dynamic-programming', correctType: '1D DP (Linear)',
    correctDS: 'dp[i] or just 2 variables',
    whyThisPattern: '"Count ways" to reach a state with small choices = DP. dp[i] = dp[i-1] + dp[i-2]. Same as Fibonacci.',
    keyTriggers: ['count ways', 'distinct ways', 'number of ways'],
    approach: 'dp[i] = dp[i-1] + dp[i-2]. Optimize to 2 vars.',
    timeComplexity: 'O(n)',
  },
  {
    id: 25, title: 'Longest Common Subsequence', difficulty: 'Medium',
    inputDesc: 'Two strings text1, text2',
    outputDesc: 'Length of their longest common subsequence',
    constraints: ['1 ≤ len ≤ 1000', 'Subsequence = can skip chars'],
    keywords: ['two strings', 'longest common', 'subsequence', 'characters in order'],
    correctPattern: 'dynamic-programming', correctType: '2D DP (Grid/Two Sequences)',
    correctDS: 'dp[m+1][n+1] 2D array',
    whyThisPattern: '"Two sequences" + "longest common" = 2D DP. dp[i][j] = LCS of text1[0..i] and text2[0..j].',
    keyTriggers: ['two strings', 'longest common subsequence', 'comparing sequences'],
    approach: 'If match: dp[i][j]=dp[i-1][j-1]+1. Else: dp[i][j]=max(dp[i-1][j], dp[i][j-1]).',
    timeComplexity: 'O(m*n)',
  },
  {
    id: 26, title: 'Coin Change', difficulty: 'Medium',
    inputDesc: 'Array coins[] (coin denominations), integer amount',
    outputDesc: 'Fewest coins needed to make up amount (-1 if impossible)',
    constraints: ['Can use unlimited coins of each type', '0 ≤ amount ≤ 10⁴'],
    keywords: ['fewest coins', 'minimum coins', 'make up amount', 'unlimited use', 'coin denominations'],
    correctPattern: 'dynamic-programming', correctType: 'Unbounded Knapsack',
    correctDS: 'dp[amount+1] 1D array',
    whyThisPattern: '"Unlimited use" + "minimize coins" = unbounded knapsack. Inner loop left→right (allows reuse).',
    keyTriggers: ['unlimited coins', 'fewest coins', 'make up amount'],
    approach: 'dp[0]=0, rest=∞. For i=1..amount: for each coin: dp[i]=min(dp[i], dp[i-coin]+1).',
    timeComplexity: 'O(n * amount)',
  },
  {
    id: 27, title: 'Partition Equal Subset Sum', difficulty: 'Medium',
    inputDesc: 'Integer array nums',
    outputDesc: 'True if array can be partitioned into two subsets with equal sum',
    constraints: ['1 ≤ nums.length ≤ 200', '1 ≤ nums[i] ≤ 100'],
    keywords: ['partition', 'two equal subsets', 'equal sum', 'subset exists'],
    correctPattern: 'dynamic-programming', correctType: '0/1 Knapsack',
    correctDS: 'dp[target+1] boolean array',
    whyThisPattern: '"Can subset sum to X" where each element used at most once = 0/1 knapsack. dp[j] = can we sum to j?',
    keyTriggers: ['partition', 'equal sum', 'subset sum', 'pick or not pick'],
    approach: 'Target=sum/2. dp[0]=true. For each num: for j=target..num: dp[j] |= dp[j-num].',
    timeComplexity: 'O(n * sum)',
  },
  // ─── Merge Intervals ───
  {
    id: 28, title: 'Merge Intervals', difficulty: 'Medium',
    inputDesc: 'Array of intervals intervals[][2]',
    outputDesc: 'Array of merged, non-overlapping intervals',
    constraints: ['intervals[i] = [start, end]', 'May have overlapping intervals'],
    keywords: ['intervals', 'overlapping', 'merge', 'combine overlapping ranges'],
    correctPattern: 'merge-intervals', correctType: 'Merge Overlapping Intervals',
    correctDS: 'Sorted array of intervals',
    whyThisPattern: '"Merge overlapping intervals" is the canonical merge intervals problem. Sort by start, then merge.',
    keyTriggers: ['intervals', 'overlapping', 'merge'],
    approach: 'Sort by start. For each: if overlaps with last → extend last.end. Else → push new.',
    timeComplexity: 'O(n log n)',
  },
  {
    id: 29, title: 'Meeting Rooms II', difficulty: 'Medium',
    inputDesc: 'Array of meeting time intervals [[start, end], ...]',
    outputDesc: 'Minimum number of conference rooms required',
    constraints: ['Multiple meetings can occur simultaneously', 'Find peak overlap'],
    keywords: ['meeting rooms', 'minimum rooms', 'overlapping meetings', 'conference rooms', 'peak overlap'],
    correctPattern: 'merge-intervals', correctType: 'Interval Scheduling (Min Rooms)',
    correctDS: 'Min-heap of end times',
    whyThisPattern: '"Minimum rooms" = count max overlapping intervals. Sort by start, min-heap tracks end times.',
    keyTriggers: ['minimum rooms', 'meeting rooms', 'how many rooms'],
    approach: 'Sort by start. Min-heap of end times. If heap.top ≤ start → pop (room free). Push end. Answer = heap size.',
    timeComplexity: 'O(n log n)',
  },
  // ─── Cyclic Sort ───
  {
    id: 30, title: 'Missing Number', difficulty: 'Easy',
    inputDesc: 'Array nums with n distinct integers from range [0, n]',
    outputDesc: 'The one missing number from the range',
    constraints: ['Values are distinct and in [0, n]', 'O(1) extra space', 'O(n) time'],
    keywords: ['missing number', 'range 0 to n', 'one number missing', 'array contains 0..n'],
    correctPattern: 'cyclic-sort', correctType: 'Find Missing Number',
    correctDS: 'Array (in-place sort) or XOR/math trick',
    whyThisPattern: '"Range [0,n], find missing" = cyclic sort. After sorting, first index where nums[i]≠i is the answer.',
    keyTriggers: ['missing number', 'range 0 to n', 'distinct integers'],
    approach: 'Cyclic sort (values 1..n to index-1). Then find first mismatch. Or: XOR(0..n) ^ XOR(all nums).',
    timeComplexity: 'O(n)',
  },
  // ─── Fast & Slow ───
  {
    id: 31, title: 'Linked List Cycle', difficulty: 'Easy',
    inputDesc: 'Head of linked list',
    outputDesc: 'True if list has a cycle (some node points back to earlier node)',
    constraints: ['O(1) extra space', 'No modification allowed', '-10⁵ ≤ values ≤ 10⁵'],
    keywords: ['linked list', 'cycle', 'loop', 'detect cycle', 'O(1) space'],
    correctPattern: 'fast-slow-pointers', correctType: 'Cycle Detection',
    correctDS: 'Two pointers (slow/fast) on linked list',
    whyThisPattern: '"Cycle in linked list" + "O(1) space" = Floyd\'s slow-fast pointers. They meet iff cycle exists.',
    keyTriggers: ['cycle', 'linked list', 'O(1) space'],
    approach: 'slow=fast=head. slow=slow.next, fast=fast.next.next. If they meet → cycle.',
    timeComplexity: 'O(n)',
  },
  // ─── Heap/Trie ───
  {
    id: 32, title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium',
    inputDesc: 'Operations: insert(word), search(word), startsWith(prefix)',
    outputDesc: 'Implement a data structure supporting these 3 operations',
    constraints: ['1 ≤ word.length ≤ 2000', 'Lowercase letters only', 'Up to 3×10⁴ operations'],
    keywords: ['prefix', 'starts with', 'word exists', 'autocomplete', 'insert search'],
    correctPattern: 'trie', correctType: 'Basic Trie (Insert/Search/Prefix)',
    correctDS: 'TrieNode { children: Map or array[26], isEnd: boolean }',
    whyThisPattern: '"Prefix search" + "starts with" = Trie is the optimal DS. O(m) per op where m=word length.',
    keyTriggers: ['prefix', 'starts with', 'autocomplete'],
    approach: 'TrieNode with children[26] and isEnd. Insert: walk/create nodes. Search: walk, check isEnd.',
    timeComplexity: 'O(m) per operation',
  },
  // ─── Graph ───
  {
    id: 33, title: 'Number of Connected Components', difficulty: 'Medium',
    inputDesc: 'n nodes (0..n-1), edges[][2] (undirected)',
    outputDesc: 'Number of connected components in the graph',
    constraints: ['Undirected graph', '0 ≤ edges.length ≤ 5000'],
    keywords: ['connected components', 'groups', 'undirected graph', 'count components'],
    correctPattern: 'graph-algorithms', correctType: 'Union-Find (Disjoint Set)',
    correctDS: 'Union-Find (parent array)',
    whyThisPattern: '"Count connected components" in undirected graph = Union-Find. Each union merges two components.',
    keyTriggers: ['connected components', 'same group', 'undirected'],
    approach: 'Init parent[i]=i. For each edge: union(u,v). Count distinct roots = components.',
    timeComplexity: 'O(n α(n)) ≈ O(n)',
  },
  {
    id: 34, title: 'Network Delay Time', difficulty: 'Medium',
    inputDesc: 'Weighted directed edges times[][3] (u,v,w), n nodes, source k',
    outputDesc: 'Minimum time for all nodes to receive signal, or -1 if impossible',
    constraints: ['Weighted graph', 'Find shortest path from k to ALL nodes', '1 ≤ n ≤ 100'],
    keywords: ['weighted', 'minimum time', 'all nodes', 'shortest path', 'signal propagation'],
    correctPattern: 'graph-algorithms', correctType: 'Dijkstra (Shortest Path Weighted)',
    correctDS: 'Min-heap (dist, node) + dist[] array',
    whyThisPattern: '"Weighted shortest path to all nodes" = Dijkstra. Non-negative weights. Return max dist.',
    keyTriggers: ['weighted', 'minimum time', 'shortest path', 'all nodes receive'],
    approach: 'Dijkstra from k. dist[k]=0, rest=∞. Min-heap. Return max(dist) or -1 if any ∞.',
    timeComplexity: 'O((V+E) log V)',
  },
  // ─── Bit Manipulation ───
  {
    id: 35, title: 'Single Number', difficulty: 'Easy',
    inputDesc: 'Array nums where every element appears twice except one',
    outputDesc: 'The element that appears only once',
    constraints: ['Every other element appears exactly twice', 'O(1) extra space', 'O(n) time'],
    keywords: ['appears once', 'all others appear twice', 'single element', 'O(1) space'],
    correctPattern: 'bit-manipulation', correctType: 'XOR Tricks',
    correctDS: 'Single integer (XOR accumulator)',
    whyThisPattern: '"One appears once, rest appear twice" + "O(1) space" = XOR. a^a=0, 0^b=b. All pairs cancel.',
    keyTriggers: ['appears once', 'others appear twice', 'O(1) space'],
    approach: 'result=0. XOR all elements. Pairs cancel, unique remains.',
    timeComplexity: 'O(n)',
  },
];

export const RECOGNITION_BY_PATTERN: Record<string, RecognitionChallenge[]> = 
  RECOGNITION_CHALLENGES.reduce((acc, c) => {
    if (!acc[c.correctPattern]) acc[c.correctPattern] = [];
    acc[c.correctPattern].push(c);
    return acc;
  }, {} as Record<string, RecognitionChallenge[]>);
